yolo_model:

  config_file:
    name: yolov3_custom.cfg
  weight_file:
    name: yolov3_custom_2000.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - notdefined
      - platform
      
